baseurl = "https://alexjreid.dev/"
title = "Alex Reid"
theme = "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableInlineShortcodes = true

enableRobotsTXT = true

googleAnalytics = "UA-156939108-1"

[params]
    author = "Alex Reid"
    env = "production"
    title = "Alex Reid"
    defaultTheme = "light"
    info = "Thoughts on cloud software engineering"
    description = "Alex Reid - thoughts on software engineering"
    keywords = ["aws", "software", "cloud", "Alex Reid"]
    mainSections = ["posts", "car"]
    useHugoToc = true
    comments = false
    showPostNavLinks = false
    showtopc = true
    showBreadCrumbs = true
    pluralizelisttitles = false

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/alexjreid"

[[params.socialIcons]]
name = "mastodon"
url = "https://hachyderm.io/@alexjreid"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/alexjreid"

[[params.socialIcons]]
name = "email"
url = "mailto:alexjreid@me.com"

[params.profileMode]
enabled = true
title = "Alex Reid"
subtitle = "Thoughts on software engineering"
imageUrl = "me.jpg"
imageTitle = "alexjreid avatar"

[[params.profileMode.buttons]]
name = "Tech ramblings"
url = "/posts"

[[params.profileMode.buttons]]
name = "Porsche 996 diary"
url = "/car"

[[params.profileMode.buttons]]
name = "Most read"
url = "/tags/greatest-hits"

[[params.profileMode.buttons]]
name = "Posts by category"
url = "/tags"