baseurl = "https://alexjreid.dev/"
title = "Alex Reid"
theme = "yinyang"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "mybranchblog"
enableRobotsTXT = true

googleAnalytics = "UA-156939108-1"

[params]
    headTitle = "Alex Reid"
    author = "Alex Reid"
    title = "Alex Reid"
    info = "Thoughts on software engineering, the cloud and data."
    description = "Alex Reid - thoughts on software engineering, the cloud and data."
    keywords = "blog,developer,data,gcp,aws,nosql,dynamodb,java,go,python,dynamodb,bigtable,reid,Alex Reid,alexjreid"
    mainSections = ["posts"]

[[params.socials]]
name = "RSS Feed"
link = "/index.xml"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/alexjreid"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/alexjreid/"
