baseurl = "https://alexjreid.dev/"
title = "Alex Reid"
theme = "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableInlineShortcodes = true

enableRobotsTXT = true

googleAnalytics = "UA-156939108-1"

[params]
    author = "Alex Reid"
    env = "production"
    title = "Alex Reid"
    defaultTheme = "light"
    info = "Thoughts on software engineering"
    description = "Alex Reid - thoughts on software engineering"
    keywords = ["aws", "software", "cloud", "dyanmodb", "envoy", "consul", "Alex Reid", "porsche"]
    mainSections = ["posts", "car"]
    useHugoToc = true
    comments = false
    showPostNavLinks = false
    showtopc = true

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/alexjreid"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/alexjreid"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexjreid/"

[params.profileMode]
enabled = true
title = "Alex Reid"
subtitle = "thoughts on software engineering... and cars"
#imageUrl = "alexjreid.jpg"
#imageTitle = "alexjreid"

[[params.profileMode.buttons]]
name = "Tech"
url = "/posts"

[[params.profileMode.buttons]]
name = "Porsche 996"
url = "/car"

[[params.profileMode.buttons]]
name = "Tags"
url = "/tags"