baseurl = "https://alexjreid.dev/"
title = "Alex Reid"
theme = "yinyang"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "mybranchblog"
enableRobotsTXT = true

googleAnalytics = "UA-156939108-1"

[params]
    headTitle = "Alex Reid"
    author = "Alex Reid"
    title = "Alex Reid"
    info = "thoughts on software engineering, clouds and data"
    description = "Alex Reid - thoughts on software engineering, clouds and data."
    keywords = "blog,developer,data,gcp,aws,nosql,dynamodb"
    mainSections = ["posts"]

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/alexjreid"
[[params.socials]]
name = "GitHub"
link = "https://github.com/alexjreid"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/alexjreid/"
