baseurl = ""
title = "mybranch.dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "mybranchblog"
enableRobotsTXT = true

googleAnalytics = "UA-156939108-1"

[params]
    author = "Alex Reid"
    info = "thoughts on software engineering, clouds and data"
    description = "Alex Reid"
    keywords = "blog,developer,personal,data,gcp,aws"
    #avatarurl = "images/alexjreid.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/alexjreid/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/alexjreid"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 3
    url = "https://github.com/alexjreid"
[[menu.main]]
    name = "Blog posts"
    weight = 1
    url  = "/posts/"
