# Custom cloud builder for hugo
# gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/hugo', '.']
- name: 'gcr.io/${PROJECT_ID}/hugo'
  args: ['--help']

images: ['gcr.io/${PROJECT_ID}/hugo']
